$(document).ready(function(){
    $("#imagedesign").click(function(){
        $("imagedesign").slideDown('1500').hide('1000');
        $('#design').show('1500');
    });
    $('#design').click(function(){
        $('#design').slideUp('1500');
        $('#imagedesign').slideDown('1500');
    });
    });

$(document).ready(function(){
    $("#imagedevelopment").click(function(){
        $("imagedevelopment").slideDown('1500').hide('1000');
        $('#development').show('1500');
    });
    $('#development').click(function(){
        $('#development').slideUp('1500');
        $('#imagedevelopment').slideDown('1500');
    });
    });

$(document).ready(function(){
    $("#imageproduct").click(function(){
        $("imageproduct").slideDown('1500').hide('1000');
        $('#product').show('1500');
    });
    $('#product').click(function(){
        $('#product').slideUp('1500');
        $('#imageproduct').slideDown('1500');
    });
    });

 $(document).ready(function(){
        $("#portfolio4").mouseover(function(){
          $("#hidden4").show();
        }).mouseout(function(){
          $("#hidden4").hide();
        });
      });

      $(document).ready(function(){
        $("#portfolio3").mouseover(function(){
          $("#hidden3").show();
        }).mouseout(function(){
          $("#hidden3").hide();
        });
      });
$(document).ready(function(){
        $("#portfolio2").mouseover(function(){
          $("#hidden2").show();
        }).mouseout(function(){
          $("#hidden2").hide();
        });
      });
      $(document).ready(function(){
        $("#portfolio1").mouseover(function(){
          $("#hidden1").show();
        }).mouseout(function(){
          $("#hidden1").hide();
        });
      });
      $(document).ready(function(){
        $("#portfolio5").mouseover(function(){
          $("#hidden5").show();
        }).mouseout(function(){
          $("#hidden5").hide();
        });
      });
      $(document).ready(function(){
        $("#portfolio6").mouseover(function(){
          $("#hidden6").show();
        }).mouseout(function(){
          $("#hidden6").hide();
        });
      });
      $(document).ready(function(){
        $("#portfolio7").mouseover(function(){
          $("#hidden7").show();
        }).mouseout(function(){
          $("#hidden7").hide();
        });
      });
      $(document).ready(function(){
        $("#portfolio8").mouseover(function(){
          $("#hidden8").show();
        }).mouseout(function(){
          $("#hidden8").hide();
        });
      });
      $(document).ready(function(){
        $("#portfolio4").mouseover(function(){
          $("#hidden4").show();
        }).mouseout(function(){
          $("#hidden4").hide();
        });
      });
